### PR TITLE
fix: run container with agent user on Linux only

### LINKED ISSUE #133: Formerly working trivy devops task now fails on Mac self-hosted agent. "Unable to locate executable file: 'getent'"
**Describe the bug**
We build a Unity based application on a Mac self hosted agent. The trivy task has been working for us for some time, but stopped working in the latest release.

**Trivy Azure Pipeline Task Verison**
1.8.7

**Hosted or Self-hosted Agent**
Self-hosted Mac agent

**Trivy as Docker?**
Trivy as Docker

**Error message**
==============================================================================
Task         : Trivy
Description  : Trivy is the world’s most popular open source vulnerability and misconfiguration scanner. It is reliable, fast, extremely easy to use, and it works wherever you need it.
Version      : 1.8.7
Author       : Aqua Security
Help         : https://github.com/aquasecurity/trivy-azure-pipelines-task
==============================================================================
Run requested using docker...
##[error]Unable to locate executable file: 'getent'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

### PR DESCRIPTION
**Pull request by bonddim**
Resolves #133

### CODE REVIEW

File: trivy-task/trivyLoader.ts [hunk 1]
```diff
@@ -73,13 +73,18 @@ async function dockerRunner(version: string): Promise<ToolRunner> {
...
   }
   // Try to get the docker group id
-  const dockerGidResult = task.execSync('getent', ['group', 'docker'], {
-    silent: true,
-  });
-  if (dockerGidResult?.stdout) {
-    const gid = dockerGidResult.stdout.split(':')[2];
-    // Add the docker group id to the container to have access to the docker socket
-    runner.line(`--group-add ${gid}`);
+  try {
```
Comment (tgermain-impirica) [inline trivy-task/trivyLoader.ts:76]: what is the downside of not adding the docker group if running on Mac?

Comment (bonddim) [reply trivy-task/trivyLoader.ts:76]: Fix will skip getent issue, but you may get docker permissions issue if your agent group is not permitted on docker socket.
For example, in such case:
```
srw-rw---- 1 root docker 0 Mar 11 16:07 /var/run/docker.sock=
```

Probably, I'll push another fix to completely ignore non-root run on non-linux system.

Comment (bonddim) [reply trivy-task/trivyLoader.ts:76]: @tgermain-impirica 
could you, pls, check if this works on your agent ?
```
dscl . -read /Groups/docker
```

Comment (tgermain-impirica) [reply trivy-task/trivyLoader.ts]: I get the error

<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)

Comment (bonddim) [reply trivy-task/trivyLoader.ts]: Thank you! 
Already pushed commit to behave as in previous version on MacOS

**Review by tgermain-impirica — APPROVED** [review]

**Comment by bonddim** [comment]
@owenrumney, pls review

**Review by owenrumney — APPROVED** [review]
